package JavaCartPro.src.model;
import java.io.Serializable;
import java.io.Serial;
import java.util.List;

/**
 * Class representing a transaction - can be a customer's purchase or a seller's addition to their inventory
 */
public class Transaction implements Serializable {
    @Serial
    private static final long serialVersionUID = 1112L;
    private final User user;
    private final List<Product> products;
    private int totalSales;
    private double revenue;
    private double costs;
    private final Discount discount;

    /**
     * Constructs a Transaction object without a discount
     * @param user user involved in the transaction
     * @param products products involved in the transaction
     */
    public Transaction(User user, List<Product> products) {
        this.user = user;
        this.products = products;
        calculateTransactionValues();
        this.discount = null;
    }

    /**
     * Constructs a Transaction object with a discount
     * @param user user involved in the transaction
     * @param products products involved in the transaction
     * @param coupon discount to be applied to a purchase
     */
    public Transaction(User user, List<Product> products, Discount coupon) {
        this.user = user;
        this.products = products;
        calculateTransactionValues();
        this.discount = coupon;
    }

    /**
     * Calculates the revenue, cost, and number of sales generated by a transaction
     */
    private void calculateTransactionValues() {
        for (Product product : products) {
            //customer purchase transaction
            if (user instanceof Customer) {
                totalSales += 1;
                revenue += product.getPrice();
                costs = 0;
            }
            //seller inventory addition transaction
            else if (user instanceof Seller) {
                costs += product.getPrice();
                totalSales = 0;
                revenue = 0;
            }
        }
        if (this.discount != null) {
            discount.applyDiscount(this);
        }
    }

    /**
     * setter function for revenue (used for discounts)
     * @param newRevenue value to set revenue to
     */
    protected void setRevenue(double newRevenue) {
        this.revenue = newRevenue;
    }

    /**
     * getter function for user
     * @return the user involved in the transaction
     */
    public User getUser() {
        return user;
    }

    /**
     * getter function for products
     * @return a list of the products involved in the transaction
     */
    public List<Product> getProducts() {
        return products;
    }

    /**
     * getter function for totalSales
     * @return the number of sales generated by the transaction
     */
    public int getTotalSales() {
        return totalSales;
    }

    /**
     * getter function for revenue
     * @return the revenue generated by the transaction
     */
    public double getRevenue() {
        return revenue;
    }

    /**
     * getter function for costs
     * @return the costs incurred by the seller through the transaction
     */
    public double getCosts() {
        return costs;
    }
}
